# Generated by Django 2.1.7 on 2019-02-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('total', models.PositiveIntegerField()),
                ('last_24_hours', models.PositiveIntegerField()),
                ('between_1_and_7_days', models.PositiveIntegerField()),
                ('more_than_7_days', models.PositiveIntegerField()),
            ],
        ),
    ]
