# Generated by Django 2.1.7 on 2019-02-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registry',
            options={'verbose_name_plural': 'Registry'},
        ),
        migrations.AlterUniqueTogether(
            name='registry',
            unique_together={('repository_name', 'username')},
        ),
    ]
