# Generated by Django 2.1.7 on 2019-02-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_auto_20190216_2141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registry',
            unique_together=set(),
        ),
    ]
